### ISSUE TITLE
Banner ads not showing up in the release build

### ISSUE THREAD

**Issue by Mudit18** [khalisafkari/react-native-smaato-ad#2]
The ad request is being registered but the banner ads are not being shown up in the release build. The same is working fine when running the app in debug mode.

**Comment by khalisafkari** [comment]
try contacting your account manager, because I myself saw in the release version of my apk the ads went well

**Comment by Mudit18** [comment]
Works in the release build only on disabling both R8 and ProGuard (minifyEnabled = false).
Is there any solution available to get this working with R8 enabled?
