### ISSUE TITLE
Banner ads center

### ISSUE THREAD

**Issue by amanur38** [khalisafkari/react-native-smaato-ad#3]
How do I center banner ad, It's showing always let align.

Thanks

**Comment by khalisafkari** [comment]
wrap in view

```javascript
<View style={{ height:250,width:'100%',alignItem:'center' }}>
<BannerAd {...props} />
</View>
```

**Comment by amanur38** [comment]
Thanks for your replay, unfortunately, it's not work

**Comment by khalisafkari** [comment]
<img src="https://i.ibb.co/7W5w1sJ/Screenshot-from-2020-10-23-11-52-57.png" alt="Screenshot-from-2020-10-23-11-52-57" border="0">


<h5>You create the banner as a child of the view and define the display style</h5>

<h5>can i see your code</h5>

```typescript
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: 'red',
          padding: 5,
        }}
      >
        <BannerAd style={{ height: '100%', maxHeight: 100, width: '100%' }} />
      </View>
```

**Comment by amanur38** [comment]
> wrap in view
> 
> ```js
> <View style={{ height:250,width:'100%',alignItem:'center' }}>
> <BannerAd {...props} />
> </View>
> ```

**alignItem** should be **alignItems**
