### ISSUE TITLE
NETWORK ERROR

### ISSUE THREAD

**Issue by johnson-india** [khalisafkari/react-native-smaato-ad#4]
Banner ads is not showing. i got a error like.

{"error": "[NETWORK_ERROR]: The ad request has not been completed due to a network connectivity issue."}

but i have a good internet connection and i added Internet permission in AndroidManifest file but still its showing like this error.

 please help me

**Comment by khalisafkari** [comment]
I don't use smaato anymore and I don't have any free time, but I'll try a little.

after I saw the code there were no major changes to the smaato sdk so this plugin should still work, but if you have problems try following the smaato document and using the latest sdk.

before that try using the smaato test id if a debug ad appears then try contacting your smaato manager if there is still an error when using the production id

**Comment by johnson-india** [comment]
> I don't use smaato anymore and I don't have any free time, but I'll try a little.
> 
> after I saw the code there were no major changes to the smaato sdk so this plugin should still work, but if you have problems try following the smaato document and using the latest sdk.
> 
> before that try using the smaato test id if a debug ad appears then try contacting your smaato manager if there is still an error when using the production id

Thanks for your reply but how to use sdk from the documentation because for me, app was crashing while use it. i think dont know how to use it for react native because they all for Java code. can you guide me?

or

can you suggest any other working ad network for react native because i tried almost all but admob only working but i don't want to use admob because it have so much restrictions. so can you suggest any other?

**Comment by khalisafkari** [comment]
You can use tapdaq.com which I still manage today and I use it in my productions

i have written a plugin for react native but i don't have time to write comprehensive documentation but if you use vscode you can take a look at vscode autocomplete


https://github.com/khalisafkari/react-native-tapdaq-ad

**Comment by johnson-india** [comment]
wow thanks. can you explain few more steps to use this package. because i add this package using npm with  my project and i added my app in tapdaq website then what i need to do?

**Comment by khalisafkari** [comment]
https://github.com/khalisafkari/react-native-tapdaq-ad/blob/master/src/index.tsx

You just need to follow the tapdaq document on their website

**Comment by johnson-india** [comment]
Really Thanks. sorry i am just new to React Native so that i asked

**Comment by johnson-india** [comment]
@khalisafkari 

[https://www.tapdaq.com/docs/en/tapdaq-android-sdk/Quickstart](url)

i followed this documentation but i can't do step 2 and 3 because its for java coding. how i can be done it? sorry i am new to react native please help me

**Comment by khalisafkari** [comment]
please make a issue in the tapdaq repo not in this repo to be more specific in each repo

**Comment by johnson-india** [comment]
@khalisafkari 
okey thanks
